### ISSUE TITLE
Error: Unknown document contentType 'SFM'

### ISSUE THREAD

**Issue by jdejoode** [mvahowe/proskomma-js#82]
Proskomma example script only accepts UFSM and UFX and not SFM.

**Comment by jdejoode** [comment]
Is it possible to use USFM (in caps) or usfm (lowercase) for the content type?

**Comment by mvahowe** [comment]
On reflection, this isn't strictly a Proskomma issue, since Proskomma only knows about text strings and content types, not suffixes. Also, this whole area will need a more ambitious, mimemagic-like solution, once we try to support non-scripture content.

In the meantime, I think I'll add a utility method to Proskomma to return a contentType for the most common USFM and USX suffixes. This will at least remove some boilerplate from scripts.

**Comment by mvahowe** [comment]
@jdejoode Just hit this with some PT-generated USFM. Added `sfm` to the possible suffixes for USFM and made all suffix matching case-insensitive.
